### ISSUE TITLE
debug log setup not working?

### ISSUE THREAD

**Issue by asirota** [aspirepress/updater-plugin#2]
I added these to my wp-config.php on dev.newpathconsulting.com

```
// AspirePress update-plugin debugging

define('AP_UPDATER_HOST_REWRITES', ['api.wordpress.org' => 'your-repo.com',]);
	
define( 'AP_UPDATER_DEBUG', true);
```

I can't find a debug log when I try updating a plugin in my wp-content folder. Any guidance?

**Comment by sarah-savage** [comment]
You'll want to define the AP_UPDATER_DEBUG_LOG_PATH to a location you can observe, where it will write the log. Let me know if that fixes your issue.

**Comment by asirota** [comment]
Ok will do but should it not log into /wp-content by default ? Where is the default log path?

**Comment by sarah-savage** [comment]
I just set it to log to ABSPATH but feel free to have it log wherever is appropriate! I'm not picky.
