### ISSUE TITLE
Update the admin section to include options for configuration

### ISSUE THREAD

**Issue by sarah-savage** [aspirepress/updater-plugin#4]
We'd like to move the API key request from the General pane into its own pane. Ideally the pane would have two sections: General and Advanced.

## General

Please include the following:

* A checkbox for "enabled" (grayed out of the API key is not provided)
* An input field that is set as a password type for entering the API key.

## Advanced

Please allow for the following configuration options:

* A checkbox to enable debugging.
* A checkbox to log responses from the server.
* An OPTIONAL path to the log location (currently defaults to ABSPATH).

Let me know if you need help!

**Comment by namithj** [comment]
Taking this up.

**Comment by asirota** [comment]
I think all the configuration settings should be exposed here -- no need to hide anything for now since we will be probably debugging for a while with it.
